import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        tertiary: "#733700",
        "tertiary-container": "#964a00",
        "primary-container": "#356287",
        "surface-dim": "#d9dadb",
        "on-background": "#191c1d",
        "error-container": "#ffdad6",
        "surface-tint": "#356286",
        "inverse-primary": "#9fcbf4",
        secondary: "#006b5f",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-secondary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-fixed-variant": "#005048",
        primary: "#194a6d",
        "on-tertiary-container": "#ffd0b2",
        "primary-fixed": "#cde5ff",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#007165",
        "surface-bright": "#f8f9fa",
        "on-surface-variant": "#424654",
        outline: "#737785",
        "on-primary-container": "#baddff",
        "primary-fixed-dim": "#9fcbf4",
        "on-primary": "#ffffff",
        "surface-container": "#edeeef",
        "inverse-surface": "#2e3132",
        "secondary-fixed-dim": "#70d8c8",
        "secondary-container": "#8df5e4",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001d32",
        "on-error-container": "#93000a",
        background: "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#311300",
        "secondary-fixed": "#8df5e4",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#194a6d",
        "tertiary-fixed-dim": "#ffb786",
        surface: "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "inverse-on-surface": "#f0f1f2",
        error: "#ba1a1a",
        brand: {
          50: "#eef2ff",
          100: "#e0e7ff",
          500: "#1d4ed8",
          700: "#1e40af",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: [
          "var(--font-plus-jakarta)",
          "Plus Jakarta Sans",
          "sans-serif",
        ],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
        "mono-grammar": [
          "var(--font-jetbrains-mono)",
          "JetBrains Mono",
          "monospace",
        ],
      },
    },
  },
  plugins: [],
};

export default config;
